export type {
  AttributeFriendlyEditorDefinition,
  ComposerWarning,
  ComposerWarningCode,
  InteractionComposerHandler,
  InteractionComposerMetadata,
  InteractionComposeResult,
  InteractionNodeSpecEntry,
  InteractionResponseDeclaration,
  NodeAttributePanelMetadata,
  QtiAreaMapEntry,
  QtiAreaMapping,
  QtiStringMapEntry,
  QtiStringMapping,
  ResponseProcessingKind,
} from '@citolab/prose-qti/interfaces';
