export type {
  AttributeFriendlyEditorDefinition,
  AttributeFieldDefinition,
  AttributeFieldOption,
  ComposerWarning,
  ComposerWarningCode,
  InteractionComposerHandler,
  InteractionComposerMetadata,
  InteractionComposeResult,
  InteractionNodeSpecEntry,
  InteractionResponseDeclaration,
  NodeAttributePanelMetadata,
  QtiAreaMapEntry,
  QtiAreaMapping,
  QtiStringMapEntry,
  QtiStringMapping,
  ResponseProcessingKind,
} from '@qti-editor/interfaces';
