/*
 * ⚠️  WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 *
 * This file is automatically generated by the schema generator script.
 * Any manual changes will be lost when the schema is regenerated.
 *
 * Generated from: src/scripts/generate-qti-schema.ts
 * Generated at: 2026-01-28T15:34:07.459Z
 */

import type { QtiElementDefinition } from '../../schema/element-definitions';

export const qtiTextEntryInteractionDefinition: QtiElementDefinition = {
  id: 'text-entry-interaction',
  nodeType: 'qti_text_entry_interaction',
  tagName: 'qti-text-entry-interaction',
  label: "Text Entry",
  description: "Inline text entry interaction.",
  icon: "📝",
  keywords: ["text","input","blank","fill","entry"],
  category: 'interaction',
  insertable: true,
  defaultAttrs: {},
  createInsertCommand: (editor) => () => {
    return editor.commands.insertNode?.('qti_text_entry_interaction', {}) ?? false;
  },
};
