/*
 * ⚠️  WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 *
 * This file is automatically generated by the schema generator script.
 * Any manual changes will be lost when the schema is regenerated.
 *
 * Generated from: src/scripts/generate-qti-schema.ts
 * Generated at: 2026-01-28T15:34:07.459Z
 */

import type { QtiElementDefinition } from '../../schema/element-definitions';

export const qtiSimpleChoiceDefinition: QtiElementDefinition = {
  id: 'simple-choice',
  nodeType: 'qti_simple_choice',
  tagName: 'qti-simple-choice',
  label: "Choice Option",
  description: "Simple choice option for interactions.",
  icon: "○",
  keywords: ["choice","option"],
  category: 'content',
  insertable: false,
  defaultAttrs: {},
  createInsertCommand: (editor) => () => {
    return editor.commands.insertNode?.('qti_simple_choice', {}) ?? false;
  },
};
