import 'prosekit/basic/style.css';
import 'prosekit/basic/typography.css';
import '@qti-editor/ui/components/code-panel';
import '@qti-editor/ui/components/composer';
import '@qti-editor/ui/components/composer-metadata-form';
import '@qti-editor/ui/components/attributes-panel';
import '@qti-editor/ui/components/toolbar';
import '@qti-editor/ui/components/items-gutter';
import '@qti-editor/ui/components/items-navigator';
import { registerLitEditorBlockHandle } from '@qti-editor/ui/components/block-handle';
import { registerLitEditorDropIndicator } from '@qti-editor/ui/components/drop-indicator';
import { registerLitEditorTableHandle } from '@qti-editor/ui/components/table-handle';
import { editorContext } from '@qti-editor/ui/components/editor-context';
import './blocks/slash-menu/index.js';
import { provide, ContextProvider } from '@lit/context';
import { createRef, ref, type Ref } from 'lit/directives/ref.js';
import { LitElement, html, type PropertyValues } from 'lit';
import { property } from 'lit/decorators.js';
import { itemContext, itemContextVariables, type ItemContext } from '@qti-editor/prosekit-integration/item-context';
import {
  blockSelectExtension,
  buildCompatibilityReport,
  defineLocalStorageDocPersistenceExtension,
  defineSemanticPasteExtension,
  nodeAttrsSyncExtension,
  readPersistedStateFromLocalStorage,
  writePersistedDocStateEnvelope,
} from '@qti-editor/prosemirror-plugins';
import { createEditor, union, type Editor } from 'prosekit/core';
import { definePlaceholder } from 'prosekit/extensions/placeholder';
import { qtiEditorEventsExtension } from '@qti-editor/prosekit-integration/events';
import { notifyQtiI18nChanged, translateQti } from '@qti-editor/interaction-shared';

import { defineBasicExtension } from '../extensions/basic-extension.js';
import { defineQtiInteractionsExtension } from '../extensions/qti-interactions-extension.js';
import { defineSlashMenuGuardExtension } from '../extensions/slash-menu-guard-extension.js';
import { exportItem, exportJson, exportPackage, exportRoundtripXml, exportXml, importJson } from '../lib/exportXml.js';
import { getAutoSaveKey } from '../lib/fileStore.js';
import { importRoundtripXml, openXmlFilePicker } from '../lib/importXml.js';

import type { CompatibilityReport } from '@qti-editor/interfaces';

function slugifyTitle(title: string): string {
  return title.trim().replace(/[^A-Za-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}
const VOID_HTML_TAGS = [
  'img', 'br', 'hr', 'input', 'meta', 'link',
  'source', 'area', 'col', 'embed', 'param', 'track', 'wbr',
];

function toXmlCompatibleFragment(html: string): string {
  const voidTagPattern = new RegExp(`<(${VOID_HTML_TAGS.join('|')})(\\s[^<>]*?)?>`, 'gi');
  return html
    .replace(/&nbsp;/g, '&#160;') // XML doesn't define &nbsp;
    .replace(voidTagPattern, match => {
      if (match.endsWith('/>')) return match;
      return `${match.slice(0, -1)} />`;
    });
}

export class QtiEditorApp extends LitElement {
  @property({ type: String, reflect: true })
  override lang = 'en';

  private editor: Editor;
  private editorRef: Ref<HTMLDivElement>;
  private composerEventTarget = new EventTarget();
  private _pendingCompatibilityReport: CompatibilityReport | undefined;

  // ── Toolbar handoff ─────────────────────────────────────────────────────
  private _editorMounted = false;
  private _currentItemIndex = 0;
  private _itemCount = 1;
  private _itemIdentifierAutogenerated: boolean[] = [true];
  private readonly _itemUuids: string[] = [crypto.randomUUID()];

  private _trackCurrentItem = () => {
    const view = (this.editor as any).view;
    if (!view?.state) return;

    const { doc, selection } = view.state;
    const cursorPos = selection.from;
    const itemPositions: number[] = [1];

    doc.descendants((node: any, pos: number) => {
      if (node.type.name === 'qtiItemDivider') {
        itemPositions.push(pos + node.nodeSize);
      }
    });

    let newIndex = 0;
    for (let i = itemPositions.length - 1; i >= 0; i--) {
      if (cursorPos >= itemPositions[i]) {
        newIndex = i;
        break;
      }
    }

    const changed = this._currentItemIndex !== newIndex || this._itemCount !== itemPositions.length;
    this._currentItemIndex = newIndex;
    this._itemCount = itemPositions.length;
    if (changed) this.requestUpdate();
  };

  private hasMetadataSelection(): boolean {
    if (!this._editorMounted) return false;

    const view = (this.editor as any).view;
    if (!view?.state) return false;

    const { doc } = view.state;
    if (doc.textContent.trim().length > 0) return true;

    let hasMeaningfulStructure = false;
    doc.descendants((node: any) => {
      const typeName = node.type?.name;
      if (typeName === 'doc' || typeName === 'text' || typeName === 'paragraph' || typeName === 'hardBreak' || typeName === 'qtiItemDivider') {
        return;
      }

      hasMeaningfulStructure = true;
      return false;
    });

    return hasMeaningfulStructure;
  }

  private onMetadataChange(event: Event) {
    const detail = (event as CustomEvent<{ title: string; identifier: string; informational: boolean }>).detail;
    const idx = this._currentItemIndex;
    const items = [...(this.itemContext.items ?? [])];
    while (items.length <= idx) items.push({ identifier: '', title: '', informational: false });
    while (this._itemIdentifierAutogenerated.length <= idx) this._itemIdentifierAutogenerated.push(true);
    while (this._itemUuids.length <= idx) this._itemUuids.push(crypto.randomUUID());

    let identifier = detail.identifier;
    if (this._itemIdentifierAutogenerated[idx]) {
      if (detail.identifier !== (items[idx].identifier ?? '')) {
        this._itemIdentifierAutogenerated[idx] = false;
      } else {
        const slug = slugifyTitle(detail.title);
        identifier = slug ? `${slug}-${this._itemUuids[idx]}` : '';
      }
    }

    items[idx] = {
      title: detail.title,
      identifier,
      informational: detail.informational,
    };

    this.itemContext = {
      ...this.itemContext,
      items,
      informationalItems: items.map(item => item.informational ?? false),
    };
  }

  @provide({ context: itemContext })
  itemContext: ItemContext = {
    lang: 'en',
    variables: itemContextVariables,
    items: [{ identifier: '', title: '', informational: false }],
  };

  constructor() {
    super();
    const editorDocStorageKey = getAutoSaveKey();

    const extension = union(
      defineBasicExtension(),
      defineQtiInteractionsExtension(),
      defineSemanticPasteExtension(),
      defineSlashMenuGuardExtension(),
      // The placeholder extension is used to mark certain nodes (e.g. interaction content)
      // so the slash menu guard can detect them and suppress the menu when the cursor is inside.
      definePlaceholder({
        placeholder: (state) => {
          const $pos = state.selection.$anchor;
          for (let d = $pos.depth; d > 0; d--) {
            const placeholder = $pos.node(d).type.spec.placeholder;
            if (placeholder) return placeholder;
          }
          return translateQti('editor.placeholder', { target: this });
        }
      }),
      defineLocalStorageDocPersistenceExtension({ storageKey: editorDocStorageKey }),
      blockSelectExtension,
      nodeAttrsSyncExtension,
      qtiEditorEventsExtension({
        emitSelectionChanges: false,
        eventTarget: this.composerEventTarget,
      }),
    );

    const restoredState = readPersistedStateFromLocalStorage(editorDocStorageKey);
    try {
      this.editor = createEditor({
        extension,
        defaultContent: restoredState.doc
      });
      const compat = restoredState.compatibility;
      if (compat && compat.sourceVersion < compat.targetVersion) {
        this._pendingCompatibilityReport = buildCompatibilityReport([{
          id: 'startup-load',
          label: 'Loaded document',
          result: compat,
        }]);
      }
    } catch {
      window.localStorage.removeItem(editorDocStorageKey);
      this.editor = createEditor({ extension });
    }
    this.editorRef = createRef<HTMLDivElement>();

    // Provider for editor context - pass editor directly (ProseKit elements handle unmounted state)
    new ContextProvider(this, {
      context: editorContext,
      initialValue: this.editor,
    });

    // Register block-handle components
    registerLitEditorBlockHandle();
    registerLitEditorDropIndicator();
    registerLitEditorTableHandle()

    this.composerEventTarget.addEventListener('qti:content:change', event => {
      const detail = (event as CustomEvent<{ html?: string }>).detail;
      const xmlCompatibleHtml = toXmlCompatibleFragment(detail?.html ?? '');
      const parsed = new DOMParser().parseFromString(
        '<qti-item-body>' + xmlCompatibleHtml + '</qti-item-body>',
        'application/xml',
      );
      this.itemContext = {
        ...this.itemContext,
        lang: this.itemContext.lang,
        itemBody: parsed,
      };
    });
  }

  override createRenderRoot() {
    return this;
  }

  override disconnectedCallback() {
    document.removeEventListener('selectionchange', this._trackCurrentItem);
    super.disconnectedCallback();
  }

  override updated(changedProperties: PropertyValues) {
    super.updated(changedProperties);

    if (changedProperties.has('lang')) {
      this.itemContext = {
        ...this.itemContext,
        lang: this.lang,
      };
      notifyQtiI18nChanged();
    }

    if (this.editorRef.value && !this._editorMounted) {
      this.editor.mount(this.editorRef.value);
      this._editorMounted = true;
      document.addEventListener('selectionchange', this._trackCurrentItem);
      this.requestUpdate(); // Re-render to pass editor.view to attributes panel
      // Defer past React's useEffect registration window.
      // updated() runs synchronously during React's DOM commit; useEffect
      // listeners aren't attached until after that commit completes.
      const pendingReport = this._pendingCompatibilityReport;
      this._pendingCompatibilityReport = undefined;
      setTimeout(() => {
        this.dispatchEvent(new CustomEvent('qti:editor:ready', {
          detail: { editor: this.editor },
          bubbles: true,
        }));
        if (pendingReport) {
          document.dispatchEvent(new CustomEvent('qti:compatibility:report', {
            detail: pendingReport,
            bubbles: true,
          }));
        }
      }, 0);
    }
  }

  exportXml(fileName: string = 'item'): void {
    exportXml({
      node: this.editor.view.state.doc,
      lang: this.lang,
      items: this.itemContext.items,
      fileName,
    });
  }

  exportItem(fileName: string = 'item'): void {
    exportItem({
      node: this.editor.view.state.doc,
      lang: this.lang,
      items: this.itemContext.items,
      fileName,
    });
  }

  async exportPackage(fileName: string = 'item'): Promise<void> {
    await exportPackage({
      node: this.editor.view.state.doc,
      lang: this.lang,
      items: this.itemContext.items,
      fileName,
    });
  }


  exportJson(fileName: string = 'item'): void {
    exportJson(this.editor.view.state.doc, fileName);
  }

  async importJson(): Promise<void> {
    try {
      const pmDoc = await importJson(this.editor.schema);
      this.editor.setContent(pmDoc.toJSON());
      localStorage.setItem(getAutoSaveKey(), JSON.stringify(writePersistedDocStateEnvelope(pmDoc.toJSON())));
      document.dispatchEvent(new CustomEvent('qti:content:change', { bubbles: true }));
    } catch (error) {
      console.error('Failed to import JSON:', error);
      alert('Failed to import JSON file. Please check that the file contains valid ProseMirror JSON.');
    }
  }

  exportRoundtripXml(fileName: string = 'item'): void {
    exportRoundtripXml(this.editor.view.state.doc, fileName);
  }

  async importRoundtripXml(): Promise<void> {
    try {
      const pmDoc = await importRoundtripXml(this.editor.schema);
      this.editor.setContent(pmDoc.toJSON());
      localStorage.setItem(getAutoSaveKey(), JSON.stringify(writePersistedDocStateEnvelope(pmDoc.toJSON())));
      document.dispatchEvent(new CustomEvent('qti:content:change', { bubbles: true }));
    } catch (error) {
      console.error('Failed to import roundtrip XML:', error);
      alert('Failed to import roundtrip XML file.');
    }
  }

  async importXml(): Promise<void> {
    try {
      const result = await openXmlFilePicker({ schema: this.editor.schema });
      this.editor.setContent(result.json);

      // Write the imported doc to localStorage immediately so saveFile() reads
      // the correct content without waiting for the persistence plugin's debounce.
      const doc = this.editor.view.state.doc.toJSON();
      localStorage.setItem(getAutoSaveKey(), JSON.stringify(writePersistedDocStateEnvelope(doc)));

      // Notify the React layer (dirty state, auto-save status) that content changed.
      document.dispatchEvent(new CustomEvent('qti:content:change', { bubbles: true }));
      if (result.compatibility?.report) {
        document.dispatchEvent(new CustomEvent('qti:compatibility:report', {
          detail: result.compatibility.report,
          bubbles: true,
        }));
      }

      // Update metadata if present
      if (result.metadata) {
        if (result.metadata.identifier) this._itemIdentifierAutogenerated[0] = false;
        const items = [...(this.itemContext.items ?? [{ identifier: '', title: '' }])];
        items[0] = {
          ...items[0],
          ...(result.metadata.title && { title: result.metadata.title }),
          ...(result.metadata.identifier && { identifier: result.metadata.identifier }),
        };
        this.itemContext = { ...this.itemContext, items };
      }
    } catch (error) {
      console.error('Failed to import XML:', error);
      alert('Failed to import XML file. Please check that the file contains valid QTI XML.');
    }
  }

  override render() {
    const currentItem = this.itemContext.items?.[this._currentItemIndex];
    const showMetadataValidation = currentItem != null && this.hasMetadataSelection();

    // Only render components that need the editor after it's mounted
    const editorComponents = this._editorMounted ? html`
      <lit-editor-toolbar .editor=${this.editor} class="block w-full shrink-0"></lit-editor-toolbar>
    ` : html`<div class="block w-full shrink-0" style="padding-left: 1rem; padding-right: 1rem; height: 40px;"></div>`;

    return html`
      ${editorComponents}
      <div class="flex flex-1 min-h-0 gap-4 p-4 overflow-hidden">
        <div class="editor-card relative flex min-w-0 flex-1 flex-col rounded-md border border-solid border-gray-200 bg-white text-black shadow-sm overflow-hidden">
          ${this._editorMounted ? html`<qti-items-gutter .editor=${this.editor}></qti-items-gutter>` : ''}
          <div class="relative flex-1 min-h-0 overflow-auto" style="padding-left: 3rem;">
            <div ${ref(this.editorRef)} class="card min-h-full px-6 py-6" style="padding-left: 1rem;"></div>
            <lit-editor-block-handle></lit-editor-block-handle>
            <lit-editor-drop-indicator></lit-editor-drop-indicator>
            <lit-editor-table-handle></lit-editor-table-handle>
          </div>
          ${this._editorMounted ? html`<qti-slash-menu .editor=${this.editor} style="display: contents;"></qti-slash-menu>` : ''}
          ${this._editorMounted ? html`<qti-composer .editor=${this.editor} class="block w-full shrink-0" style="position: relative; z-index: 10;"></qti-composer>` : ''}
        </div>
        <div class="w-80 shrink-0 overflow-y-auto">
          <qti-composer-metadata-form
            class="block w-full"
            .title=${currentItem?.title ?? ''}
            .identifier=${currentItem?.identifier ?? ''}
            .itemCount=${this._itemCount}
            .isInformational=${currentItem?.informational ?? false}
            .showValidation=${showMetadataValidation}
            @metadata-change=${this.onMetadataChange}
          ></qti-composer-metadata-form>
          ${this._editorMounted ? html`<qti-attributes-panel
            .editor=${this.editor}
            class="block w-full sticky top-0 mt-5"
          ></qti-attributes-panel>` : ''}
          ${this._editorMounted ? html`<qti-items-navigator
            .editor=${this.editor}
            class="block w-full mt-5"
          ></qti-items-navigator>` : ''}
        </div>
      </div>
    `;
  }
}

// Register and initialize
customElements.define('qti-editor-app', QtiEditorApp);

declare global {
  interface HTMLElementTagNameMap {
    'qti-editor-app': QtiEditorApp;
  }
}
