/*
 * ⚠️  WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
 *
 * This file is automatically generated by the schema generator script.
 * Any manual changes will be lost when the schema is regenerated.
 *
 * Generated from: src/scripts/generate-qti-schema.ts
 * Generated at: 2026-01-28T15:34:07.459Z
 */

import type { QtiElementDefinition } from '../../schema/element-definitions';

export const qtiChoiceInteractionDefinition: QtiElementDefinition = {
  id: 'choice-interaction',
  nodeType: 'qti_choice_interaction',
  tagName: 'qti-choice-interaction',
  label: "Multiple Choice",
  description: "Choice interaction container.",
  icon: "☑️",
  keywords: ["choice","quiz","mcq","select","multiple"],
  category: 'interaction',
  insertable: true,
  defaultAttrs: {},
  createInsertCommand: (editor) => () => {
    return editor.commands.insertNode?.('qti_choice_interaction', {}) ?? false;
  },
};
