import 'prosekit/basic/style.css';
import 'prosekit/basic/typography.css';
import '@citolab/prose-qti-ui/components/attributes-panel';
import './blocks/code-panel/index.js';
import './blocks/composer/index.js';
import './blocks/toolbar/index.js';
import './blocks/items-gutter/index.js';
import './blocks/items-navigator/index.js';


import './blocks/slash-menu/index.js';
import { provide, ContextProvider } from '@lit/context';
import { createRef, ref, type Ref } from 'lit/directives/ref.js';
import { LitElement, html, type PropertyValues } from 'lit';
import { property } from 'lit/decorators.js';
import { itemContext, itemContextVariables, type ItemContext, type PerItemMetadata } from '@citolab/prose-qti/integration/item-context';
import {
  blockSelectExtension,
  buildCompatibilityReport,
  defineLocalStorageDocPersistenceExtension,
  defineSemanticPasteExtension,
  nodeAttrsSyncExtension,
  readPersistedStateFromLocalStorage,
  stampSchemaVersion,
} from '@citolab/prose-extensions/prosemirror';
import { createEditor, union, type Editor } from 'prosekit/core';
import { definePlaceholder } from 'prosekit/extensions/placeholder';
import { qtiEditorEventsExtension } from '@citolab/prose-qti/integration/events';
import { editorContext } from '@citolab/prose-qti/integration/editor-context';
import { notifyQtiI18nChanged, translateQti } from '@citolab/prose-qti/components/shared';

import { registerLitEditorTableHandle } from './blocks/table-handle/index.js';
import { registerLitEditorDropIndicator } from './blocks/drop-indicator/index.js';
import { registerLitEditorBlockHandle } from './blocks/block-handle/index.js';
import { defineBasicExtension } from '../extensions/basic-extension.js';
import { defineQtiInteractionsExtension } from '../extensions/qti-interactions-extension.js';
import { defineLockedHeaderExtension, LOCKED_HEADER_DEFAULT_CONTENT, ensureLockedHeader } from '../extensions/locked-header-extension.js';
import { defineItemDividerExtension } from '../extensions/item-divider-extension.js';
import { defineSlashMenuGuardExtension } from '../extensions/slash-menu-guard-extension.js';
import { exportItem, exportJson, exportPackage, exportRoundtripXml, importJson } from '../lib/exportXml.js';
import { getAutoSaveKey } from '../lib/fileStore.js';
import { importRoundtripXml, openXmlFilePicker } from '../lib/importXml.js';

import type { CompatibilityReport } from '@citolab/prose-qti/interfaces';

function slugifyTitle(title: string): string {
  return title.trim().replace(/[^A-Za-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}
const VOID_HTML_TAGS = [
  'img', 'br', 'hr', 'input', 'meta', 'link',
  'source', 'area', 'col', 'embed', 'param', 'track', 'wbr',
];

function toXmlCompatibleFragment(html: string): string {
  const voidTagPattern = new RegExp(`<(${VOID_HTML_TAGS.join('|')})(\\s[^<>]*?)?>`, 'gi');
  return html
    .replace(/&nbsp;/g, '&#160;') // XML doesn't define &nbsp;
    .replace(voidTagPattern, match => {
      if (match.endsWith('/>')) return match;
      return `${match.slice(0, -1)} />`;
    });
}

export class QtiEditorApp extends LitElement {
  @property({ type: String, reflect: true })
  override lang = 'en';

  private editor: Editor;
  private editorRef: Ref<HTMLDivElement>;
  private composerEventTarget = new EventTarget();
  private _pendingCompatibilityReport: CompatibilityReport | undefined;

  // ── Toolbar handoff ─────────────────────────────────────────────────────
  private _editorMounted = false;
  private _currentItemIndex = 0;
  private _itemCount = 1;
  private _docIdentifierAutogenerated = true;
  private readonly _docUuid = crypto.randomUUID();

  private _trackCurrentItem = () => {
    const view = (this.editor as any).view;
    if (!view?.state) return;

    const { doc, selection } = view.state;
    const cursorPos = selection.from;
    const itemPositions: number[] = [1];

    doc.descendants((node: any, pos: number) => {
      if (node.type.name === 'qtiItemDivider') {
        itemPositions.push(pos + node.nodeSize);
      }
    });

    let newIndex = 0;
    for (let i = itemPositions.length - 1; i >= 0; i--) {
      if (cursorPos >= itemPositions[i]) {
        newIndex = i;
        break;
      }
    }

    const changed = this._currentItemIndex !== newIndex || this._itemCount !== itemPositions.length;
    this._currentItemIndex = newIndex;
    this._itemCount = itemPositions.length;
    if (changed) this.requestUpdate();
  };

  /**
   * Listens for attribute-panel edits on the doc node. When the user types in the
   * panel's `title` field and the identifier is still auto-generated, regenerate
   * the slugged identifier. Any explicit edit to `identifier` switches off the
   * auto-generate flag for the rest of the session.
   */
  private onPanelAttributesChange = (event: Event) => {
    const detail = (event as CustomEvent<{ attrs: Record<string, unknown>; pos: number }>).detail;
    if (!detail || detail.pos !== -1) return; // doc node only

    const view = (this.editor as any).view;
    if (!view?.state) return;

    if ('identifier' in detail.attrs) {
      this._docIdentifierAutogenerated = false;
      return;
    }

    if (!('title' in detail.attrs) || !this._docIdentifierAutogenerated) return;
    const nextTitle = (detail.attrs.title as string) ?? '';
    const slug = slugifyTitle(nextTitle);
    const nextIdentifier = slug ? `${slug}-${this._docUuid}` : '';
    const currentIdentifier = (view.state.doc.attrs.identifier as string) ?? '';
    if (nextIdentifier === currentIdentifier) return;
    view.dispatch(view.state.tr.setDocAttribute('identifier', nextIdentifier));
  };

  private _recomputeItems = () => {
    // editor.view is a throwing getter while the editor isn't mounted yet —
    // this listener can fire synchronously from a plugin view() during mount.
    let doc: any;
    try {
      doc = this.editor.view.state.doc;
    } catch {
      return;
    }

    const items: PerItemMetadata[] = [{
      title: (doc.attrs.title as string) ?? '',
      identifier: (doc.attrs.identifier as string) ?? '',
    }];
    doc.descendants((node: any) => {
      if (node.type.name === 'qtiItemDivider') {
        items.push({
          title: (node.attrs.title as string) ?? '',
          identifier: (node.attrs.identifier as string) ?? '',
        });
      }
    });

    const sameLength = (this.itemContext.items?.length ?? 0) === items.length;
    const unchanged = sameLength && items.every((item, i) => {
      const prev = this.itemContext.items?.[i];
      return prev?.title === item.title && prev?.identifier === item.identifier;
    });
    if (unchanged) return;

    this.itemContext = { ...this.itemContext, items };
    this.dispatchEvent(new CustomEvent('qti:metadata:change', {
      detail: { title: items[0].title ?? '', identifier: items[0].identifier ?? '' },
      bubbles: true,
      composed: true,
    }));
  };

  @provide({ context: itemContext })
  itemContext: ItemContext = {
    lang: 'en',
    variables: itemContextVariables,
    items: [{ identifier: '', title: '' }],
  };

  constructor() {
    super();
    const editorDocStorageKey = getAutoSaveKey();

    const extension = union(
      defineBasicExtension(),
      defineQtiInteractionsExtension(),
      defineItemDividerExtension(),
      defineLockedHeaderExtension(),
      defineSemanticPasteExtension(),
      defineSlashMenuGuardExtension(),
      // The placeholder extension is used to mark certain nodes (e.g. interaction content)
      // so the slash menu guard can detect them and suppress the menu when the cursor is inside.
      definePlaceholder({
        placeholder: (state) => {
          const $pos = state.selection.$anchor;
          for (let d = $pos.depth; d > 0; d--) {
            const placeholder = $pos.node(d).type.spec.placeholder;
            if (placeholder) return placeholder;
          }
          return translateQti('editor.placeholder', { target: this });
        }
      }),
      defineLocalStorageDocPersistenceExtension({ storageKey: editorDocStorageKey }),
      blockSelectExtension,
      nodeAttrsSyncExtension,
      qtiEditorEventsExtension({
        emitSelectionChanges: false,
        eventTarget: this.composerEventTarget,
      }),
    );

    const restoredState = readPersistedStateFromLocalStorage(editorDocStorageKey);
    try {
      this.editor = createEditor({
        extension,
        defaultContent: ensureLockedHeader(restoredState.doc),
      });
      const compat = restoredState.compatibility;
      if (compat && compat.sourceVersion < compat.targetVersion) {
        this._pendingCompatibilityReport = buildCompatibilityReport([{
          id: 'startup-load',
          label: 'Loaded document',
          result: compat,
        }]);
      }
    } catch {
      window.localStorage.removeItem(editorDocStorageKey);
      this.editor = createEditor({ extension, defaultContent: LOCKED_HEADER_DEFAULT_CONTENT });
    }
    this.editorRef = createRef<HTMLDivElement>();

    // Provider for editor context - pass editor directly (ProseKit elements handle unmounted state)
    new ContextProvider(this, {
      context: editorContext,
      initialValue: this.editor,
    });

    // Register block-handle components
    registerLitEditorBlockHandle();
    registerLitEditorDropIndicator();
    registerLitEditorTableHandle()

    this.composerEventTarget.addEventListener('qti:content:change', event => {
      const detail = (event as CustomEvent<{ html?: string }>).detail;
      const xmlCompatibleHtml = toXmlCompatibleFragment(detail?.html ?? '');
      const parsed = new DOMParser().parseFromString(
        '<qti-item-body>' + xmlCompatibleHtml + '</qti-item-body>',
        'application/xml',
      );
      this.itemContext = {
        ...this.itemContext,
        lang: this.itemContext.lang,
        itemBody: parsed,
      };
      this._recomputeItems();
    });
  }

  override createRenderRoot() {
    return this;
  }

  override disconnectedCallback() {
    document.removeEventListener('selectionchange', this._trackCurrentItem);
    super.disconnectedCallback();
  }

  override updated(changedProperties: PropertyValues) {
    super.updated(changedProperties);

    if (changedProperties.has('lang')) {
      this.itemContext = {
        ...this.itemContext,
        lang: this.lang,
      };
      notifyQtiI18nChanged();
    }

    if (this.editorRef.value && !this._editorMounted) {
      this.editor.mount(this.editorRef.value);
      this._editorMounted = true;
      document.addEventListener('selectionchange', this._trackCurrentItem);
      const view = (this.editor as any).view;
      if (view?.state?.doc.attrs.identifier) this._docIdentifierAutogenerated = false;
      this._recomputeItems();
      this.requestUpdate(); // Re-render to pass editor.view to attributes panel
      // Defer past React's useEffect registration window.
      // updated() runs synchronously during React's DOM commit; useEffect
      // listeners aren't attached until after that commit completes.
      const pendingReport = this._pendingCompatibilityReport;
      this._pendingCompatibilityReport = undefined;
      setTimeout(() => {
        this.dispatchEvent(new CustomEvent('qti:editor:ready', {
          detail: { editor: this.editor },
          bubbles: true,
        }));
        if (pendingReport) {
          document.dispatchEvent(new CustomEvent('qti:compatibility:report', {
            detail: pendingReport,
            bubbles: true,
          }));
        }
      }, 0);
    }
  }

  exportItem(fileName: string = 'item'): void {
    exportItem({
      node: this.editor.view.state.doc,
      lang: this.lang,
      items: this.itemContext.items,
      fileName,
    });
  }

  async exportPackage(fileName: string = 'item'): Promise<void> {
    await exportPackage({
      node: this.editor.view.state.doc,
      lang: this.lang,
      items: this.itemContext.items,
      fileName,
    });
  }


  exportJson(fileName: string = 'item'): void {
    exportJson(this.editor.view.state.doc, fileName);
  }

  async importJson(): Promise<void> {
    try {
      const pmDoc = await importJson(this.editor.schema);
      this.editor.setContent(pmDoc.toJSON());
      localStorage.setItem(getAutoSaveKey(), JSON.stringify(stampSchemaVersion(pmDoc.toJSON())));
      document.dispatchEvent(new CustomEvent('qti:content:change', { bubbles: true }));
    } catch (error) {
      console.error('Failed to import JSON:', error);
      alert('Failed to import JSON file. Please check that the file contains valid ProseMirror JSON.');
    }
  }

  exportRoundtripXml(fileName: string = 'item'): void {
    exportRoundtripXml(this.editor.view.state.doc, fileName);
  }

  async importRoundtripXml(): Promise<void> {
    try {
      const pmDoc = await importRoundtripXml(this.editor.schema);
      this.editor.setContent(pmDoc.toJSON());
      localStorage.setItem(getAutoSaveKey(), JSON.stringify(stampSchemaVersion(pmDoc.toJSON())));
      document.dispatchEvent(new CustomEvent('qti:content:change', { bubbles: true }));
    } catch (error) {
      console.error('Failed to import roundtrip XML:', error);
      alert('Failed to import roundtrip XML file.');
    }
  }

  async importXml(): Promise<void> {
    try {
      const result = await openXmlFilePicker({ schema: this.editor.schema });
      this.editor.setContent(result.json);

      // Write the imported doc to localStorage immediately so saveFile() reads
      // the correct content without waiting for the persistence plugin's debounce.
      const doc = this.editor.view.state.doc.toJSON();
      localStorage.setItem(getAutoSaveKey(), JSON.stringify(stampSchemaVersion(doc)));

      // Notify the React layer (dirty state, auto-save status) that content changed.
      document.dispatchEvent(new CustomEvent('qti:content:change', { bubbles: true }));
      if (result.compatibility?.report) {
        document.dispatchEvent(new CustomEvent('qti:compatibility:report', {
          detail: result.compatibility.report,
          bubbles: true,
        }));
      }

      // Update metadata if present
      if (result.metadata) {
        if (result.metadata.identifier) this._docIdentifierAutogenerated = false;
        const view = (this.editor as any).view;
        if (view?.state) {
          const tr = view.state.tr;
          if (result.metadata.title) tr.setDocAttribute('title', result.metadata.title);
          if (result.metadata.identifier) tr.setDocAttribute('identifier', result.metadata.identifier);
          view.dispatch(tr);
        }
        this._recomputeItems();
      }
    } catch (error) {
      console.error('Failed to import XML:', error);
      alert('Failed to import XML file. Please check that the file contains valid QTI XML.');
    }
  }

  override render() {
    // Only render components that need the editor after it's mounted
    const editorComponents = this._editorMounted ? html`
      <lit-editor-toolbar .editor=${this.editor} class="block w-full shrink-0"></lit-editor-toolbar>
    ` : html`<div class="block w-full shrink-0" style="padding-left: 1rem; padding-right: 1rem; height: 40px;"></div>`;

    return html`
      ${editorComponents}
      <div class="flex flex-1 min-h-0 gap-4 p-4 overflow-hidden">
        <div class="editor-card relative flex min-w-0 flex-1 flex-col rounded-md border border-solid border-gray-200 bg-white text-black shadow-sm overflow-hidden">
          ${this._editorMounted ? html`<qti-items-gutter .editor=${this.editor}></qti-items-gutter>` : ''}
          <div class="relative flex-1 min-h-0 overflow-auto" style="padding-left: 3rem;">
            <div ${ref(this.editorRef)} class="card min-h-full px-6 py-6 prose" style="padding-left: 1rem;"></div>
            <lit-editor-block-handle></lit-editor-block-handle>
            <lit-editor-drop-indicator></lit-editor-drop-indicator>
            <lit-editor-table-handle></lit-editor-table-handle>
          </div>
          ${this._editorMounted ? html`<qti-slash-menu .editor=${this.editor} style="display: contents;"></qti-slash-menu>` : ''}
          ${this._editorMounted ? html`<qti-composer .editor=${this.editor} class="block w-full shrink-0" style="position: relative; z-index: 10;"></qti-composer>` : ''}
        </div>
        <div class="w-80 shrink-0 overflow-y-auto">
          ${this._editorMounted ? html`<qti-attributes-panel
            .editor=${this.editor}
            class="block w-full sticky top-0"
            @qti:attributes:change=${this.onPanelAttributesChange}
          ></qti-attributes-panel>` : ''}
          ${this._editorMounted ? html`<qti-items-navigator
            .editor=${this.editor}
            class="block w-full mt-5"
          ></qti-items-navigator>` : ''}
        </div>
      </div>
    `;
  }
}

// Register and initialize
customElements.define('qti-editor-app', QtiEditorApp);

declare global {
  interface HTMLElementTagNameMap {
    'qti-editor-app': QtiEditorApp;
  }
}
